### ISSUE TITLE
Microservices checklist

### ISSUE THREAD

**Issue by goeppes** [revaturelabs/sierra#12]
High priority
- [ ] ECS cluster (includes autoscaling)
- [ ] Load Balancer
- [ ] Network (VPCs, subnets)
- [ ] Pipeline
- [ ] Service (task definitions included)
- [ ] Python script

Low priority
- [ ] Monitoring
- [ ] CloudFormation pipeline
- [ ] Disaster Recovery
